name: Automated Tests Hardware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Print Working Directory
      run: pwd

    - name: List Files
      run: ls -la

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image for Software Tests
      run: docker build -f Dockerfile.software . -t ${{ secrets.DOCKER_USERNAME }}/software-image:latest

    - name: Push Docker Image for Software Tests
      run: docker push ${{ secrets.DOCKER_USERNAME }}/software-image:latest

    - name: Run Software Tests Inside Docker
      run: docker run ${{ secrets.DOCKER_USERNAME }}/software-image:latest