name: Automated Tests Hardware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Print Working Directory
      run: pwd

    - name: List Files
      run: ls -la

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image for Hardware Tests
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.hardware
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/hardware-image:latest

    - name: Run Hardware Tests Inside Docker
      run: docker run ${{ secrets.DOCKER_USERNAME }}/hardware-image:latest
